-- Die VereinsDB für die Tabellenerstellung auswählen
USE VEREIN_DATABASE;

-- Tabellen für die VereinsDB erstellen
-- Tabelle: FUNKTION
CREATE TABLE FUNKTION (
    FUNKID INT NOT NULL,
    BEZEICHNER VARCHAR(20) NOT NULL,
    PRIMARY KEY (FUNKID)
);

-- Tabelle: STATUS
CREATE TABLE STATUS (
    STATID INT NOT NULL,
    BEZEICHNER VARCHAR(20) NOT NULL,
    BEITRAG DECIMAL(5),
    PRIMARY KEY (STATID),
    CHECK (BEITRAG IS NULL OR BEITRAG >= 0)
);

-- Tabelle: PERSON
CREATE TABLE PERSON (
    PERSID INT NOT NULL,
    NAME VARCHAR(20) NOT NULL,
    VORNAME VARCHAR(15) NOT NULL,
    STRASSE_NR VARCHAR(20) NOT NULL,
    PLZ CHAR(4) NOT NULL,
    ORT VARCHAR(20) NOT NULL,
    BEZAHLT CHAR(1) NOT NULL,
    BEMERKUNGEN VARCHAR(50),
    EINTRITT DATE,
    AUSTRITT DATE,
    STATID INT NOT NULL,
    MENTORID INT,
    PRIMARY KEY (PERSID),
    CHECK ((EINTRITT <= AUSTRITT OR AUSTRITT IS NULL) OR (EINTRITT IS NULL AND AUSTRITT IS NULL)),
    FOREIGN KEY (MENTORID) REFERENCES PERSON(PERSID),
    FOREIGN KEY (STATID) REFERENCES STATUS(STATID)
);

-- Tabelle: FUNKTIONSBESETZUNG
CREATE TABLE FUNKTIONSBESETZUNG (
    ANTRITT DATE NOT NULL,
    RUECKTRITT DATE,
    FUNKID INT NOT NULL,
    PERSID INT NOT NULL,
    PRIMARY KEY (FUNKID, PERSID, ANTRITT),
    CHECK (ANTRITT <= RUECKTRITT OR RUECKTRITT IS NULL),
    FOREIGN KEY (FUNKID) REFERENCES FUNKTION(FUNKID),
    FOREIGN KEY (PERSID) REFERENCES PERSON(PERSID)
);

-- Tabelle: ANLASS
CREATE TABLE ANLASS (
    ANLAID INT NOT NULL,
    BEZEICHNER VARCHAR(20) NOT NULL,
    ORT VARCHAR(20),
    DATUM DATE NOT NULL,
    KOSTEN DECIMAL(8, 2),
    ORGID INT NOT NULL,
    PRIMARY KEY (ANLAID),
    CHECK (KOSTEN IS NULL OR KOSTEN >= 0)
);

-- Tabelle: SPONSOR
CREATE TABLE SPONSOR (
    SPONID INT NOT NULL,
    NAME VARCHAR(20) NOT NULL,
    STRASSE_NR VARCHAR(20) NOT NULL,
    PLZ CHAR(4) NOT NULL,
    ORT VARCHAR(20) NOT NULL,
    SPENDENTOTAL DECIMAL(8, 2) NOT NULL,
    PRIMARY KEY (SPONID)
);

-- Tabelle: SPENDE
CREATE TABLE SPENDE (
    SPENID INT NOT NULL,
    BEZEICHNER VARCHAR(20),
    DATUM DATE DEFAULT CURRENT_DATE NOT NULL,
    BETRAG DECIMAL(8, 2) NOT NULL,
    SPONID INT NOT NULL,
    ANLAID INT,
    PRIMARY KEY (SPENID, SPONID),
    FOREIGN KEY (ANLAID) REFERENCES ANLASS(ANLAID),
    FOREIGN KEY (SPONID) REFERENCES SPONSOR(SPONID)
);

-- Tabelle: SPONSORENKONTAKT
CREATE TABLE SPONSORENKONTAKT (
    PERSID INT NOT NULL,
    SPONID INT NOT NULL,
    PRIMARY KEY (PERSID, SPONID),
    FOREIGN KEY (PERSID) REFERENCES PERSON(PERSID),
    FOREIGN KEY (SPONID) REFERENCES SPONSOR(SPONID)
);

-- Tabelle: TEILNEHMER
CREATE TABLE TEILNEHMER (
    PERSID INT NOT NULL,
    ANLAID INT NOT NULL,
    PRIMARY KEY (PERSID, ANLAID),
    FOREIGN KEY (ANLAID) REFERENCES ANLASS(ANLAID),
    FOREIGN KEY (PERSID) REFERENCES PERSON(PERSID)
);

-- Fremdschlüssel-Constraints hinzufügen
ALTER TABLE ANLASS ADD CONSTRAINT ANLASS_PERSON_FK FOREIGN KEY (ORGID) REFERENCES PERSON(PERSID);

ALTER TABLE SPONSORENKONTAKT ADD CONSTRAINT FK_SPONK_PERSON FOREIGN KEY (PERSID) REFERENCES PERSON(PERSID);

ALTER TABLE SPONSORENKONTAKT ADD CONSTRAINT FK_SPONK_SPONSOR FOREIGN KEY (SPONID) REFERENCES SPONSOR(SPONID);

ALTER TABLE TEILNEHMER ADD CONSTRAINT FK_TEILN_ANLASS FOREIGN KEY (ANLAID) REFERENCES ANLASS(ANLAID);

ALTER TABLE TEILNEHMER ADD CONSTRAINT FK_TEILN_PERSON FOREIGN KEY (PERSID) REFERENCES PERSON(PERSID);

ALTER TABLE FUNKTIONSBESETZUNG ADD CONSTRAINT FUNKTIONSBESETZUNG_FUNKTION_FK FOREIGN KEY (FUNKID) REFERENCES FUNKTION(FUNKID);

ALTER TABLE FUNKTIONSBESETZUNG ADD CONSTRAINT FUNKTIONSBESETZUNG_PERSON_FK FOREIGN KEY (PERSID) REFERENCES PERSON(PERSID);

ALTER TABLE PERSON ADD CONSTRAINT PERSON_PERSON_FK FOREIGN KEY (MENTORID) REFERENCES PERSON(PERSID);

ALTER TABLE PERSON ADD CONSTRAINT PERSON_STATUS_FK FOREIGN KEY (STATID) REFERENCES STATUS(STATID);

ALTER TABLE SPENDE ADD CONSTRAINT SPENDE_ANLASS_FK FOREIGN KEY (ANLAID) REFERENCES ANLASS(ANLAID);

ALTER TABLE SPENDE ADD CONSTRAINT SPENDE_SPONSOR_FK FOREIGN KEY (SPONID) REFERENCES SPONSOR(SPONID);